disabled_rules:
- implicit_return
- multiple_closures_with_trailing_closure
- cyclomatic_complexity

excluded:
- Pods
- Carthage
- vendor
- .vendor

opt_in_rules:
- prohibited_super_call
- overridden_super_call
- private_outlet
- private_action
- private_over_fileprivate
- anyobject_protocol
- closure_spacing
- contains_over_first_not_nil
- discouraged_optional_collection
- first_where
- implicit_return
- joined_default_parameter
- operator_usage_whitespace
- redundant_nil_coalescing
- redundant_type_annotation
- empty_string
- force_unwrapping

file_length:
- 1000
- 1500

line_length: 300

type_body_length:
- 400 # warning
- 600 # error

large_tuple:
- 5 # warning
- 7 # error

identifier_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 60
    error: 80
  excluded:
  - vc
  - to
  - x
  - y
  - i

function_body_length:
- 100 # warning
- 200 # error

force_cast: warning
force_try: error
force_unwrapping: error
private_outlet: error
